// Crops, resizes and compresses the source photos in assets/photos into
// public/images, then writes blur previews for every image to
// src/lib/image-blur.ts.
//
// To add a photo: put it in assets/photos, add or edit an entry below,
// then run `node scripts/optimize-images.mjs`.
import fs from "node:fs";
import path from "node:path";
import sharp from "sharp";

const root = path.join(import.meta.dirname, "..");
const src = (f) => path.join(root, "assets", "photos", f);
const out = path.join(root, "public", "images");

/**
 * extract: region of the source to keep, as fractions of width/height.
 * aspect: output width / height. width: max output width.
 * blur: optional gaussian sigma, baked into the file (hides low resolution).
 */
const photos = [
  { out: "hero", source: "locksmith-door.jpg", width: 1920, aspect: 16 / 10, flop: true, blur: 2.5, quality: 70 },
  { out: "door-opening", source: "locksmith-door.jpg", width: 1000, aspect: 4 / 5, extract: { left: 0.13, top: 0, width: 0.5, height: 1 } },
  { out: "key-copy", source: "key-cutting.jpg", width: 1000, aspect: 4 / 5 },
  { out: "process-bg", source: "keys-wood.jpg", width: 1920, aspect: 2 },
  { out: "trust", source: "keys-wood.jpg", width: 1200, aspect: 4 / 3, extract: { left: 0.4, top: 0, width: 0.6, height: 1 } },
  { out: "cta-bg", source: "key-wall.webp", width: 1920, aspect: 2, extract: { left: 0, top: 0, width: 0.94, height: 0.82 } },
  { out: "location", source: "key-wall.webp", width: 1920, aspect: 16 / 9, extract: { left: 0, top: 0, width: 0.94, height: 0.82 } },
  { out: "key-hand", source: "keys-yellow.jpg", width: 1000, aspect: 10 / 11 },
  { out: "blog-keys-inside", source: "keys-yellow.jpg", width: 1000, aspect: 4 / 3 },
  { out: "blog-anti-theft", source: "key-wall.webp", width: 1000, aspect: 4 / 3, extract: { left: 0.05, top: 0, width: 0.75, height: 0.6 } },
  { out: "blog-price", source: "key-cutting.jpg", width: 1000, aspect: 4 / 3, extract: { left: 0, top: 0.4, width: 1, height: 0.6 } },
  { out: "cylinder", source: "key-cutting.jpg", width: 1000, aspect: 4 / 5, extract: { left: 0.25, top: 0.35, width: 0.6, height: 0.5 } },
  // Unsplash License photos (images.unsplash.com IDs listed in README)
  { out: "smart-lock", source: "us-smart-lock-phone.jpg", width: 1000, aspect: 4 / 5 },
  { out: "blog-smart-lock", source: "us-smart-lock-phone.jpg", width: 1000, aspect: 4 / 3 },
  { out: "anti-theft", source: "us-vault-door.jpg", width: 1000, aspect: 4 / 5 },
  { out: "emergency", source: "us-house-dusk.jpg", width: 1000, aspect: 4 / 5, extract: { left: 0.28, top: 0, width: 0.5, height: 1 } },
  { out: "portrait", source: "us-craftsman.jpg", width: 900, aspect: 3 / 4 },
];

for (const p of photos) {
  let img = sharp(src(p.source)).rotate();
  const meta = await img.metadata();
  let w = meta.width;
  let h = meta.height;
  if (p.extract) {
    const e = p.extract;
    const region = {
      left: Math.round(e.left * w),
      top: Math.round(e.top * h),
      width: Math.round(e.width * w),
      height: Math.round(e.height * h),
    };
    img = sharp(await img.extract(region).toBuffer());
    w = region.width;
    h = region.height;
  }
  if (p.flop) img = img.flop();
  // Never upscale beyond 1.5x the source: it only adds bytes, not detail.
  const width = Math.min(p.width, Math.round(Math.min(w, h * p.aspect) * 1.5));
  img = img.resize({ width, height: Math.round(width / p.aspect), fit: "cover", position: p.position ?? "attention" });
  if (p.blur) img = sharp(await img.toBuffer()).blur(p.blur);
  await img
    .jpeg({ quality: p.quality ?? 78, mozjpeg: true, progressive: true })
    .toFile(path.join(out, `${p.out}.jpg`));
  console.log("wrote", p.out, width);
}

const blur = {};
for (const f of fs.readdirSync(out).filter((f) => f.endsWith(".jpg")).sort()) {
  const buf = await sharp(path.join(out, f)).resize(10).jpeg({ quality: 50 }).toBuffer();
  blur[`/images/${f}`] = `data:image/jpeg;base64,${buf.toString("base64")}`;
}
fs.writeFileSync(
  path.join(root, "src", "lib", "image-blur.ts"),
  `// Generated by scripts/optimize-images.mjs — do not edit.\nexport const blurData: Record<string, string> = ${JSON.stringify(blur, null, 2)};\n\nexport function blurProps(src: string) {\n  const blurDataURL = blurData[src];\n  return blurDataURL ? ({ placeholder: "blur", blurDataURL } as const) : {};\n}\n`,
);
console.log("wrote blur map for", Object.keys(blur).length, "images");
